# NUMPY

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.2'

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,20,5)

array([10, 15])

In [12]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
np.arange(20,10) #1st arg <2nd arg

array([], dtype=int64)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.zeros(5) #parameter tuning

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5,dtype=int)#hayper parameter tuning

array([0, 0, 0, 0, 0])

In [17]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.array([2,10])

array([ 2, 10])

In [20]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
#np.array([2,10])--
#2-always be rows
#10-always be colume

In [22]:
np.ones(2)

array([1., 1.])

In [23]:
np.ones(2,dtype=int)

array([1, 1])

In [24]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [25]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
arr

array([0, 1, 2, 3, 4, 5])

In [27]:
rand(3,2)

NameError: name 'rand' is not defined

In [28]:
random.rand(3,2)

NameError: name 'random' is not defined

In [29]:
np.random.rand(3,2)

array([[0.01378179, 0.02624525],
       [0.21184391, 0.11947623],
       [0.78394497, 0.59925383]])

In [30]:
np.random.rand(3)

array([0.44109734, 0.35069169, 0.96605241])

In [31]:
np.random.randint(4,6)

4

In [32]:
np.random.randint(0,10)

2

In [33]:
np.random.randint(0,10,4)

array([1, 2, 7, 3], dtype=int32)

In [34]:
np.random.randint(0,10,5)

array([2, 9, 9, 1, 4], dtype=int32)

In [35]:
n = np.random.randint(10,40,(8,10))

In [36]:
n

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [23, 39, 29, 38, 26, 38, 29, 14, 32, 35],
       [27, 29, 19, 11, 39, 10, 23, 26, 30, 19],
       [15, 31, 29, 19, 28, 37, 33, 37, 22, 25]], dtype=int32)

In [37]:
n[5]

array([23, 39, 29, 38, 26, 38, 29, 14, 32, 35], dtype=int32)

In [38]:
n

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [23, 39, 29, 38, 26, 38, 29, 14, 32, 35],
       [27, 29, 19, 11, 39, 10, 23, 26, 30, 19],
       [15, 31, 29, 19, 28, 37, 33, 37, 22, 25]], dtype=int32)

In [39]:
n[0:6]

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [23, 39, 29, 38, 26, 38, 29, 14, 32, 35]], dtype=int32)

In [40]:
n

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [23, 39, 29, 38, 26, 38, 29, 14, 32, 35],
       [27, 29, 19, 11, 39, 10, 23, 26, 30, 19],
       [15, 31, 29, 19, 28, 37, 33, 37, 22, 25]], dtype=int32)

In [41]:
n[0]

array([37, 25, 33, 22, 30, 33, 18, 16, 24, 10], dtype=int32)

In [42]:
n[::-1]

array([[15, 31, 29, 19, 28, 37, 33, 37, 22, 25],
       [27, 29, 19, 11, 39, 10, 23, 26, 30, 19],
       [23, 39, 29, 38, 26, 38, 29, 14, 32, 35],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [37, 25, 33, 22, 30, 33, 18, 16, 24, 10]], dtype=int32)

In [43]:
n

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [23, 39, 29, 38, 26, 38, 29, 14, 32, 35],
       [27, 29, 19, 11, 39, 10, 23, 26, 30, 19],
       [15, 31, 29, 19, 28, 37, 33, 37, 22, 25]], dtype=int32)

In [44]:
n[::1]

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [23, 39, 29, 38, 26, 38, 29, 14, 32, 35],
       [27, 29, 19, 11, 39, 10, 23, 26, 30, 19],
       [15, 31, 29, 19, 28, 37, 33, 37, 22, 25]], dtype=int32)

In [45]:
n[::2]

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [27, 29, 19, 11, 39, 10, 23, 26, 30, 19]], dtype=int32)

In [46]:
n

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [23, 39, 29, 38, 26, 38, 29, 14, 32, 35],
       [27, 29, 19, 11, 39, 10, 23, 26, 30, 19],
       [15, 31, 29, 19, 28, 37, 33, 37, 22, 25]], dtype=int32)

In [47]:
n[0]

array([37, 25, 33, 22, 30, 33, 18, 16, 24, 10], dtype=int32)

In [48]:
n

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32],
       [23, 39, 29, 38, 26, 38, 29, 14, 32, 35],
       [27, 29, 19, 11, 39, 10, 23, 26, 30, 19],
       [15, 31, 29, 19, 28, 37, 33, 37, 22, 25]], dtype=int32)

In [49]:
n[0:5]

array([[37, 25, 33, 22, 30, 33, 18, 16, 24, 10],
       [22, 34, 31, 21, 31, 34, 15, 39, 11, 39],
       [33, 16, 33, 13, 31, 37, 35, 31, 20, 31],
       [23, 39, 25, 28, 18, 11, 22, 30, 35, 28],
       [17, 24, 28, 17, 30, 16, 32, 29, 24, 32]], dtype=int32)

In [50]:
n[0,5] #in matrix(,) specific position

np.int32(33)

In [51]:
n[5,-3]

np.int32(14)

In [52]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
print(n[5,-3])

14


In [54]:
import numpy as np

x= np.int32(10)
print(x)

10


In [55]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [56]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [57]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [58]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# indexing

In [59]:
mat=np.arange(0,100).reshape(10,10)

In [60]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [61]:
row = 4
col = 5

In [62]:
col

5

In [63]:
row

4

In [64]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [65]:
mat[row,col]

np.int64(45)

In [66]:
mat[4,5]

np.int64(45)

In [68]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [70]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# with slicing
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [ ]:
mat[col] #how to print rows

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [72]:
mat[:,row]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [74]:
mat[row]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [75]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [77]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [83]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [80]:
row

4

In [78]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [84]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [85]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [88]:
mat[col:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [90]:
mat[1:2,2:4]

array([[12, 13]])

In [91]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

# masking

In [92]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
id(mat)

1552620812976

In [94]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [95]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [96]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [97]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [98]:
mat[mat=50]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2537316517.py, line 1)

In [99]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [101]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# python program generate otp

In [2]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 0503


In [3]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [4]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [5]:
list1= ['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x000001866C3E09C0>


In [6]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]


In [ ]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [104]:
pip install pyplot

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement pyplot (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pyplot
