# NUMPY

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.2'

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [165]:
print(type(arr))

<class 'numpy.ndarray'>


In [166]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [147]:
np.arange(10,20,5)

array([10, 15])

In [168]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [169]:
np.arange(20,10) #1st arg <2nd arg

array([], dtype=int64)

In [170]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [171]:
np.zeros(5) #parameter tuning

array([0., 0., 0., 0., 0.])

In [172]:
np.zeros(5,dtype=int)#hayper parameter tuning

array([0, 0, 0, 0, 0])

In [173]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [174]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [175]:
np.array([2,10])

array([ 2, 10])

In [8]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [176]:
#np.array([2,10])--
#2-always be rows
#10-always be colume

In [177]:
np.ones(2)

array([1., 1.])

In [178]:
np.ones(2,dtype=int)

array([1, 1])

In [179]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [180]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [181]:
rand(3,2)

NameError: name 'rand' is not defined

In [182]:
random.rand(3,2)

NameError: name 'random' is not defined

In [183]:
np.random.rand(3,2)

array([[0.72476657, 0.78870341],
       [0.49915007, 0.14275745],
       [0.36986816, 0.08415568]])

In [184]:
np.random.rand(3)

array([0.90877998, 0.72670888, 0.21021539])

In [185]:
np.random.randint(4,6)

5

In [186]:
np.random.randint(0,10)

3

In [10]:
np.random.randint(0,10,4)

array([2, 8, 1, 7], dtype=int32)

In [187]:
np.random.randint(0,10,5)

array([5, 4, 5, 0, 2], dtype=int32)

In [12]:
n = np.random.randint(10,40,(8,10))

In [13]:
n

array([[30, 18, 13, 37, 17, 16, 31, 16, 13, 33],
       [21, 12, 38, 24, 32, 26, 17, 34, 36, 23],
       [16, 17, 10, 13, 18, 23, 12, 24, 16, 30],
       [24, 33, 37, 22, 13, 30, 36, 28, 19, 24],
       [24, 34, 22, 26, 28, 28, 23, 26, 15, 27],
       [35, 29, 16, 28, 29, 31, 36, 39, 11, 34],
       [29, 15, 17, 20, 23, 12, 17, 34, 31, 37],
       [16, 17, 31, 24, 15, 18, 24, 30, 30, 23]], dtype=int32)

In [198]:
n[5]

array([26, 29, 18, 23, 29, 28, 20, 36, 19, 24], dtype=int32)

In [14]:
n

array([[30, 18, 13, 37, 17, 16, 31, 16, 13, 33],
       [21, 12, 38, 24, 32, 26, 17, 34, 36, 23],
       [16, 17, 10, 13, 18, 23, 12, 24, 16, 30],
       [24, 33, 37, 22, 13, 30, 36, 28, 19, 24],
       [24, 34, 22, 26, 28, 28, 23, 26, 15, 27],
       [35, 29, 16, 28, 29, 31, 36, 39, 11, 34],
       [29, 15, 17, 20, 23, 12, 17, 34, 31, 37],
       [16, 17, 31, 24, 15, 18, 24, 30, 30, 23]], dtype=int32)

In [199]:
n[0:6]

array([[24, 18, 32, 28, 25, 20, 18, 31, 15, 26],
       [18, 18, 19, 17, 30, 34, 28, 21, 15, 12],
       [26, 32, 33, 27, 16, 11, 14, 27, 13, 18],
       [30, 32, 17, 30, 25, 13, 16, 12, 14, 25],
       [36, 17, 28, 30, 25, 25, 36, 11, 33, 32],
       [26, 29, 18, 23, 29, 28, 20, 36, 19, 24]], dtype=int32)

In [15]:
n

array([[30, 18, 13, 37, 17, 16, 31, 16, 13, 33],
       [21, 12, 38, 24, 32, 26, 17, 34, 36, 23],
       [16, 17, 10, 13, 18, 23, 12, 24, 16, 30],
       [24, 33, 37, 22, 13, 30, 36, 28, 19, 24],
       [24, 34, 22, 26, 28, 28, 23, 26, 15, 27],
       [35, 29, 16, 28, 29, 31, 36, 39, 11, 34],
       [29, 15, 17, 20, 23, 12, 17, 34, 31, 37],
       [16, 17, 31, 24, 15, 18, 24, 30, 30, 23]], dtype=int32)

In [192]:
n[0]

array([39, 36, 13, 35, 21, 21, 27, 21, 17, 16], dtype=int32)

In [200]:
n[::-1]

array([[24, 25, 15, 14, 14, 24, 33, 25, 30, 15],
       [34, 27, 12, 22, 25, 18, 39, 39, 24, 11],
       [31, 34, 21, 11, 28, 32, 26, 10, 21, 20],
       [14, 31, 23, 33, 11, 35, 31, 21, 39, 25],
       [26, 29, 18, 23, 29, 28, 20, 36, 19, 24],
       [36, 17, 28, 30, 25, 25, 36, 11, 33, 32],
       [30, 32, 17, 30, 25, 13, 16, 12, 14, 25],
       [26, 32, 33, 27, 16, 11, 14, 27, 13, 18],
       [18, 18, 19, 17, 30, 34, 28, 21, 15, 12],
       [24, 18, 32, 28, 25, 20, 18, 31, 15, 26]], dtype=int32)

In [201]:
n

array([[24, 18, 32, 28, 25, 20, 18, 31, 15, 26],
       [18, 18, 19, 17, 30, 34, 28, 21, 15, 12],
       [26, 32, 33, 27, 16, 11, 14, 27, 13, 18],
       [30, 32, 17, 30, 25, 13, 16, 12, 14, 25],
       [36, 17, 28, 30, 25, 25, 36, 11, 33, 32],
       [26, 29, 18, 23, 29, 28, 20, 36, 19, 24],
       [14, 31, 23, 33, 11, 35, 31, 21, 39, 25],
       [31, 34, 21, 11, 28, 32, 26, 10, 21, 20],
       [34, 27, 12, 22, 25, 18, 39, 39, 24, 11],
       [24, 25, 15, 14, 14, 24, 33, 25, 30, 15]], dtype=int32)

In [202]:
n[::1]

array([[24, 18, 32, 28, 25, 20, 18, 31, 15, 26],
       [18, 18, 19, 17, 30, 34, 28, 21, 15, 12],
       [26, 32, 33, 27, 16, 11, 14, 27, 13, 18],
       [30, 32, 17, 30, 25, 13, 16, 12, 14, 25],
       [36, 17, 28, 30, 25, 25, 36, 11, 33, 32],
       [26, 29, 18, 23, 29, 28, 20, 36, 19, 24],
       [14, 31, 23, 33, 11, 35, 31, 21, 39, 25],
       [31, 34, 21, 11, 28, 32, 26, 10, 21, 20],
       [34, 27, 12, 22, 25, 18, 39, 39, 24, 11],
       [24, 25, 15, 14, 14, 24, 33, 25, 30, 15]], dtype=int32)

In [203]:
n[::2]

array([[24, 18, 32, 28, 25, 20, 18, 31, 15, 26],
       [26, 32, 33, 27, 16, 11, 14, 27, 13, 18],
       [36, 17, 28, 30, 25, 25, 36, 11, 33, 32],
       [14, 31, 23, 33, 11, 35, 31, 21, 39, 25],
       [34, 27, 12, 22, 25, 18, 39, 39, 24, 11]], dtype=int32)

In [204]:
n

array([[24, 18, 32, 28, 25, 20, 18, 31, 15, 26],
       [18, 18, 19, 17, 30, 34, 28, 21, 15, 12],
       [26, 32, 33, 27, 16, 11, 14, 27, 13, 18],
       [30, 32, 17, 30, 25, 13, 16, 12, 14, 25],
       [36, 17, 28, 30, 25, 25, 36, 11, 33, 32],
       [26, 29, 18, 23, 29, 28, 20, 36, 19, 24],
       [14, 31, 23, 33, 11, 35, 31, 21, 39, 25],
       [31, 34, 21, 11, 28, 32, 26, 10, 21, 20],
       [34, 27, 12, 22, 25, 18, 39, 39, 24, 11],
       [24, 25, 15, 14, 14, 24, 33, 25, 30, 15]], dtype=int32)

In [205]:
n[0]

array([24, 18, 32, 28, 25, 20, 18, 31, 15, 26], dtype=int32)

In [210]:
n

array([[24, 18, 32, 28, 25, 20, 18, 31, 15, 26],
       [18, 18, 19, 17, 30, 34, 28, 21, 15, 12],
       [26, 32, 33, 27, 16, 11, 14, 27, 13, 18],
       [30, 32, 17, 30, 25, 13, 16, 12, 14, 25],
       [36, 17, 28, 30, 25, 25, 36, 11, 33, 32],
       [26, 29, 18, 23, 29, 28, 20, 36, 19, 24],
       [14, 31, 23, 33, 11, 35, 31, 21, 39, 25],
       [31, 34, 21, 11, 28, 32, 26, 10, 21, 20],
       [34, 27, 12, 22, 25, 18, 39, 39, 24, 11],
       [24, 25, 15, 14, 14, 24, 33, 25, 30, 15]], dtype=int32)

In [213]:
n[0:5]

array([[24, 18, 32, 28, 25, 20, 18, 31, 15, 26],
       [18, 18, 19, 17, 30, 34, 28, 21, 15, 12],
       [26, 32, 33, 27, 16, 11, 14, 27, 13, 18],
       [30, 32, 17, 30, 25, 13, 16, 12, 14, 25],
       [36, 17, 28, 30, 25, 25, 36, 11, 33, 32]], dtype=int32)

In [ ]:
n[0,5] #in matrix(,) specific position

np.int32(20)

In [215]:
n[5,-3]

np.int32(36)

In [216]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [218]:
print(n[5,-3])

36


In [ ]:
import numpy as np

x= np.int32(10)
print(x)

10


In [219]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [220]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [222]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])