In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
year = int(input("Enter a year: "))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
     print("Leap Year")
else:
     print("Not a Leap Year")

Enter a year:  2027


Not a Leap Year


In [66]:
i = 1
while i <= 5:
    print("data science")
    i = i + 1

data science
data science
data science
data science
data science


In [67]:
i = 1
while i <= 2:
    j = 0
    while j <= 2:
        print(i*j, end = "")
        j+=1
    print()
    i +=1

012
024


In [68]:
i = 1
while i <= 4:
    j = 0
    while j <= 3:
        print(i*j, end = "")
        j+=1
    print()
    i +=1

0123
0246
0369
04812


In [69]:
name = 'mamta'
for i in name:
    print(i)

m
a
m
t
a


## name1 = [1,2,3,'hello']
for i in name1:
    print(i)

In [9]:
for i in range(5):
    print(i)

0
1
2
3
4


In [10]:
for i in range(1, 10, 3):
    print(i)

1
4
7


In [11]:
for i in range(1,51):
    if i % 5 == 0:
        print(i)

5
10
15
20
25
30
35
40
45
50


In [13]:
for i in range(1,30):
    if i % 5 != 0:
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29


In [16]:
for i in range(1,11):
    if i == 8:
        break
    print(i)

1
2
3
4
5
6
7


In [17]:
for i in range(1,11):
    if i == 8:
        continue
    print(i)

1
2
3
4
5
6
7
9
10


In [18]:
for i in range(1,11):
    pass

In [21]:
x = int(input("How many chocolate you want:?"))
i = 1
while i <= x:
    print("chocalate")
    i += 1

How many chocolate you want:? 8


chocalate
chocalate
chocalate
chocalate
chocalate
chocalate
chocalate
chocalate


In [22]:
avg = 5
x = int(input("How many chocalate you want:?"))
i = 1
while i <= x:
    print("chocalate")
    i += 1

How many chocalate you want:? 9


chocalate
chocalate
chocalate
chocalate
chocalate
chocalate
chocalate
chocalate
chocalate


In [25]:
avilable = 5
x = int(input("How many chocolate you want:?"))
i = 1
while i <= x:
    if i > avilable:
        print("Out of stock")
        break
    print("chocolate")
    i += 1
print("bye for now")

How many chocolate you want:? 6


chocolate
chocolate
chocolate
chocolate
chocolate
Out of stock
bye for now


In [26]:
for i in range(1,51):
    if i % 3 == 0:
        print(i)
print('end')

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
end


In [27]:
for i in range(1,51):
    if i % 3 == 0:
        continue
        print(i)
print('end')

end


In [28]:
for i in range(1, 51):
    if i % 3 == 0 or i % 5 == 0:
        continue
    print(i)
print('end')

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


In [29]:
nums = [12,14,18,21,30,40]
for num in nums:
    if num % 5 == 0:
        print(num)

30
40


In [31]:
nums = [12,14,18,21,20,25]
for num in nums:
    if num % 5 == 0:
        print(num)
        break

20


In [32]:
nums = [12,14,18,21,30,40]
for num in nums:
    if num % 5 == 0:
        print(num)
else:
    print("number not found")

30
40
number not found


In [33]:
nums = [12,14,18,21,27,4,7,9]
for num in nums:
    if num % 5 == 0:
        print(num)
else:
    print("number not found")

number not found


In [39]:
#patters in python
for i in range(1,5):
    i = i+ 1
    print(" # # # #")

 # # # #
 # # # #
 # # # #
 # # # #


In [70]:
for i in range(1,5):
    if i <= 5:
        print(" # # # #")

 # # # #
 # # # #
 # # # #
 # # # #


In [71]:
for j in range (4):
    print('#')

#
#
#
#


In [72]:
for j in range (4):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [73]:
for j in range(4):
    print('#',end = " ")

# # # # 

In [74]:
for j in range(4):
    print('#',end = " ")
for j in range(4):
    print('#',end = " ")

# # # # # # # # 

In [75]:
for i in range(4):
    for j in range(4):
        print('#',end = " ")
    print()

# # # # 
# # # # 
# # # # 
# # # # 


In [76]:
for i in range(4):
    for j in range( i +1):
         print('#', end = " ")
    print()

# 
# # 
# # # 
# # # # 


In [77]:
for i in range(4):
    for j in range(4-i):
         print('#', end = " ")
    print()

# # # # 
# # # 
# # 
# 


In [78]:
num = 13
for i in range (2, num):
    if num % i == 0:
        print(num,"is not prime number")
        break
else:
    print(num,"is a prime number")        

13 is a prime number


In [79]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [80]:
print(arr.dtype)

int32


In [81]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [82]:
print(arr.dtype)

float64


In [83]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [86]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuas
arr4


array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [87]:
arr4 = np.arange(0, 10, 2) 
arr4

array([0, 2, 4, 6, 8])

Right angle Triangle Pattern

In [88]:
for i in range(1,6):
    print('*' * i)

*
**
***
****
*****


Inverted Right angle Triangle

In [92]:
for i in range(5,0,-1):
    print('*' * i)

*****
****
***
**
*


Pyramid Pattern

In [93]:
for i in range(1,6):
    print(''*(5-i)+' * '*(2*i-1))

 * 
 *  *  * 
 *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  *  *  *  *  * 


In [94]:
for i in range(5,0,-1):
    print(''*(5-i)+' * '*(2*i-1))

 *  *  *  *  *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  * 
 *  *  * 
 * 


In [97]:
for i in range(1,6):
    print(''*(5-i)+' * '*(2*i-1))
for i in range(4,0,-1):
    print(''*(5-i)+' * '*(2*i-1))

 * 
 *  *  * 
 *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  * 
 *  *  * 
 * 


In [2]:
for i in range(5):
    for j in range(5):
        if i == 0 or i == 4 or j == 0 or j == 4:
            print('*', end="")
        else:
            print(' ', end='')
    print()


*****
*   *
*   *
*   *
*****


In [3]:
for i in range(5):
    print(' * '*5)

 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 


In [7]:
row = 5
for i in range (1, row +1):
    for j in range(1, i+1):
        print(j, end=" ")
    print()
    

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [11]:
rows = 5
for i in range(rows , 0, -1):
    for j in range(1, i+1):
        print(j, end =" ")
    print()

1 2 3 4 5 
1 2 3 4 
1 2 3 
1 2 
1 


In [12]:
num = 1
for i in range(1,6):
    for j in range(1, i+1):
        print(num, end=' ')
        num+=1
    print()

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [15]:
for i in range(1,6):
    for j in range(1, i+1):
        if j == 1 or j == i or i ==5:
            print('*',end = ' ')
        else:
            print(' ',end=' ')
    print()

* 
* * 
*   * 
*     * 
* * * * * 


In [19]:
for i in range(1,6):
    for j in range(5 - i):
        print(' ',end=' ')
    for j in range(2 * i - 1):
        if j == 0 or j == 2 * i - 2 or i == 5:
            print('*',end=' ')
        else:
            print(' ',end=' ')
    print()

        * 
      *   * 
    *       * 
  *           * 
* * * * * * * * * 


In [20]:
n  = 5 
for i in range(1,n+1):
    for j in range (n - i):
        print(' ', end='')
    for j in range (2*i-1):
        if j==0 or j == 2 * i-2:
            print('*',end='')
        else:
            print(' ',end='')
    print()

for i in range(n-1, 0, -1):
    for j in range (n - i):
        print(' ', end='')
    for j in range (2*i-1):
        if j==0 or j == 2 * i-2:
            print('*',end='')
        else:
            print(' ',end='')
    print()

    *
   * *
  *   *
 *     *
*       *
 *     *
  *   *
   * *
    *


In [21]:
n  = 5 
for i in range(1,n+1):
    for j in range (n - i):
        print(' ', end='')
    for j in range (2*i-1):
        if j==0 or j == 2 * i-2:
            print(i,end='')
        else:
            print(' ',end='')
    print()

for i in range(n-1, 0, -1):
    for j in range (n - i):
        print(' ', end='')
    for j in range (2*i-1):
        if j==0 or j == 2 * i-2:
            print(i,end='')
        else:
            print(' ',end='')
    print()

    1
   2 2
  3   3
 4     4
5       5
 4     4
  3   3
   2 2
    1


In [26]:
rows = 5

for i in range(1, rows + 1):
    print(" " * (row - i),end = " ")
    print("* " * i)

     * 
    * * 
   * * * 
  * * * * 
 * * * * * 


In [27]:
rows = 5

for i in range(1, rows + 1):
    print("* " * i)

rows = 5

for i in range(1, rows + 1):
    for j in range(1, i+1):
        print(j,end=" ")
    print()    

* 
* * 
* * * 
* * * * 
* * * * * 
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [28]:
rows = 5

for i in range(1, rows + 1):
    for j in range(1, i+1):
        print(j,end=" ")
    print()    

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [31]:
rows = 5

for i in range(1, rows + 1):
    for j in range(rows-i):
        print(' ', end= ' ')
    for j in range(1, i+1):
        print(j, end=' ')
    print()

rows = 5

for i in range(1, rows + 1):
    for j in range(rows-i):
        print(' ', end= ' ')
    for j in range(i):
        print('*',end= ' ')
    print()   

        1 
      1 2 
    1 2 3 
  1 2 3 4 
1 2 3 4 5 
        * 
      * * 
    * * * 
  * * * * 
* * * * * 
